/*
 * GTimer
 *
 * Copyright:
 *      (C) 1999 Craig Knudsen, cknudsen@radix.net
 *      See accompanying file "COPYING".
 *
 *      This program is free software; you can redistribute it and/or
 *      modify it under the terms of the GNU General Public License
 *      as published by the Free Software Foundation; either version 2
 *      of the License, or (at your option) any later version.
 *
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 *
 *      You should have received a copy of the GNU General Public License
 *      along with this program; if not, write to the
 *      Free Software Foundation, Inc., 59 Temple Place,
 *      Suite 330, Boston, MA  02111-1307, USA
 *
 * Description:
 *	This file is generated AUTOMATICALLY from ./txt2h.pl.
 *	DO NOT EDIT THIS FILE!!!!
 *
  ****************************************************************************/

static char *changelog_text = "\
Release 2.0.0 (25 Mar 2010)\n\
  + Update to GTK 1.2 (Patch from Pavel Vavra)\n\
  + Inclusion or a large series of Debian patches:\n\
    Russ Allbery <rra@debian.org>  Sat, 26 Jul 2008 12:46:27 -0700\n\
    * Add a desktop file and icon, courtesy of Ubuntu.  Thanks, Nathan\n\
      Handler.  (Closes: #492498, LP: #248346)\n\
    * Reference the icon in the menu file as well.\n\
    * Fix the doc-base section (remove the Applications prefix).\n\
    * Use filter instead of findstring to parse DEB_BUILD_OPTIONS.\n\
    * Update standards version to 3.8.0.\n\
      - Add README.source explaining the dbs system.\n\
\n\
    Russ Allbery <rra@debian.org>  Sat, 29 Dec 2007 16:45:57 -0800\n\
    * Fix segfault when displaying HTML reports introduced by the patch to\n\
      make the browser configurable.  Thanks to Chad Skeeters for the\n\
      patch.\n\
    * Change menu section to Applications/Project Management per the new\n\
      menu policy.\n\
    * Add a Homepage control field.\n\
    * Update standards version to 3.7.3.\n\
    * Wrap Build-Depends for readability.\n\
\n\
    Russ Allbery <rra@debian.org>  Sat, 20 May 2006 22:31:51 -0700\n\
    * Choosing revert after an idle was subtracting time from all instances\n\
      of that task, not just the running one.  Fixed.  Thanks to Ricardo\n\
      Lopes Pereira for the report.  (Closes: #366762)\n\
    * Always pass the host and build types to configure.\n\
\n\
    Russ Allbery <rra@debian.org>  Mon, 27 Feb 2006 00:37:01 -0800\n\
    * Fix a segfault on daily reports when tasks have annotations and\n\
      annotation data is requested.  (Closes: #350711)\n\
    * Add a Last Year report.  Thanks, Bruno Gravato.  (Closes: #353046)\n\
    * Don't compress the contrib scripts.\n\
    * Add the build-indep and binary-indep targets.\n\
    * Clean up stamp file handling in debian/rules.\n\
\n\
    Russ Allbery <rra@debian.org>  Sat,  3 Dec 2005 11:12:33 -0800\n\
    * Providing binary-indep in debian/rules is required by Policy even if\n\
      there are no arch-independent packages.  Whoops.\n\
    * Mark install target as phony in debian/rules.\n\
\n\
    Russ Allbery <rra@stanford.edu>  Mon,  3 Oct 2005 15:52:11 -0700\n\
    * Add README.Debian explaining how to get started and describing the\n\
      user-visible changes relative to stock GTimer.\n\
    * Add an explicit packaging copyright and license statement.\n\
    * Update the FSF address in copyright.\n\
\n\
    Russ Allbery <rra@stanford.edu>  Fri, 15 Jul 2005 23:41:44 -0700\n\
    * Build-depend on libxss-dev instead of xlibs-static-dev for the X\n\
      transition.\n\
    * Add a -weekstart command-line option to set the first day of the week\n\
      for weekly reports.  (Closes: #307634)\n\
    * Use the user's locale for weekday names as well.\n\
    * Default to sensible-browser rather than x-www-browser and separate\n\
      that patch out from the patch to make the browser configurable.\n\
    * Fix the erroneous change to open modes in 10_57969-printpipe.patch so\n\
      that 22_276011-reportmode.patch is no longer necessary.\n\
    * 21_193517-oneMinIncr.diff subsumes 10_40450-32bitism.patch, so drop\n\
      the latter.\n\
    * Add history log entries at the top of the affected files in each patch\n\
      rather than adding comments at the location of the change, with the\n\
      exception of the Debian-specific change to turn off checks for newer\n\
      versions.\n\
    * Build with debugging symbols by default and support noopt.\n\
    * Remove some bits from debian/rules that weren't being used.\n\
\n\
    Russ Allbery <rra@stanford.edu>  Wed, 29 Jun 2005 18:21:16 -0700\n\
    * Only change the configured window size on exit if the call to get the\n\
      window size succeeds, rather than changing it to some random value off\n\
      the stack.  Partially fixes #309779.\n\
\n\
    Russ Allbery <rra@stanford.edu>  Fri, 20 May 2005 10:05:56 -0700\n\
    * Revert and Resume now only revert times on the timers that were\n\
      running, rather than all timers that had time for that day.  Fixes a\n\
      bug introduced in the last release.  Thanks to Jamm!n Wheeler for the\n\
      report.  (Closes: #309937)\n\
\n\
    Russ Allbery <rra@stanford.edu>  Mon, 18 Apr 2005 02:00:11 -0700\n\
    * Specify a file mode when saving reports.  (Closes: #276011)\n\
    * Add a dialog box to configure the browser, which allows us to stop\n\
      suggesting Netscape.  Default to x-www-browser in the absence of any\n\
      configuration.  (Closes: #38052, #138840)\n\
    * Revert and Resume after an idle now really back up to before the idle,\n\
      not just when the dialog box is displayed.  Revert now makes sure\n\
      GTimer knows it has stopped.  (Closes: #282052, #64175)\n\
    * Avoid memory clobber when saving projects that caused long-term\n\
      instability.  Thanks, Ove Kaaven.  (Closes: #201091)\n\
    * Don't depend on libc6-dev.\n\
    * Depend on xlibs-static-dev instead of xlibs-dev as libXss.a is the\n\
      only bit of X we call directly.  libgtk will pull in the rest.\n\
    * Quote strings properly in the menu entry.\n\
    * Improve the long description of the package.\n\
    * Update debhelper compatibility to V4.\n\
    * Add a watch file.\n\
    * General reformatting and cleanup of the Debian control files.\n\
\n\
    Martin Hicks <mort@bork.org>  Fri,  2 Jan 2004 17:27:00 -0500\n\
    * Add a callback to allow clearing of the paste buffer.\n\
      Partial Close: Bug#193517\n\
    * More increment and decrement shortcut keys and one\n\
      minute increment and decrement.  Finishes up: Bug#193517\n\
    * Dates in the report should now follow the user's Locale.\n\
      Closes: Bug#204322\n\
    * Moving files seems to break dbs so i removed the patch\n\
      called 10_87440-rename_cz_to_cs.patch and replaced it with\n\
      a small patch to debian/rules sent by Chad Walstrom.\n\
    * Updated to required debhelper >= 3.0.0\n\
\n\
    Chad Walstrom <chewie@debian.org>  Fri,  9 May 2003 19:19:32 -0500\n\
    * Switch to DBS build process, separated individual fixes in the \"patches\"\n\
      directory.  Should be easier to send patches upstream.\n\
    * Moved po/cz.po to po/cs.po.  Closes: Bug#87740\n\
    * Shortcutted the version_timeout_handler() function to bypass version\n\
      checking. Closes: Bug#109329\n\
\n\
    Chad C. Walstrom <chewie@debian.org>  Fri, 23 Feb 2001 01:07:18 -0600\n\
    * Changed 'Recommends:' field in the control file to 'Suggests:' so\n\
      we can keep the package in main.\n\
    * Added 'Build-Depends' field in debian/control\n\
\n\
    Chad C. Walstrom <chewie@debian.org>  Thu, 22 Feb 2001 00:57:20 -0600\n\
    * Added netscape to the 'Recommends:' field of the control file.\n\
      This software has hard-coded the use of netscape as the viewer of\n\
      the HTML report, unfortunately.\n\
\n\
    Chad C. Walstrom <chewie@debian.org>  Thu, 22 Feb 2001 00:14:49 -0600\n\
    * Reapplied fix for 32-bit-isms noted earlier by David.  Closes: Bug#40450\n\
\n\
    Wichert Akkerman <wakkerma@debian.org>  Sun, 20 Feb 2000 15:22:43 +0100\n\
    * Fix unsafe /tmp usage with patch from BTS. Closes: Bug#57969\n\
\n\
    David Huggins-Daines <dhd@debian.org>  Tue, 29 Jun 1999 14:15:10 -0400\n\
    * Fixed a bug which would cause the main window to never be shown (on\n\
      Alpha at least).\n\
    * Fixed some (probably harmless) 32-bit-isms.\n\
    * Fixed the menu entry.\n\
\n\
19 Mar 2003:\n\
  - Release 1.1.6\n\
    + Fixed bug that would sometimes cause annotations to be truncated.\n\
    + Added cut/copy/paste in new \"Edit\" menu.\n\
      Use can store time in the cut/paste buffer:\n\
        User can cut all time from selected task for current day. (Ctrl-X)\n\
        User can decrement time from selected task for current day.\n\
      Paste will apply stored in the cut/paste buffer to the currently\n\
      selected task.\n\
    + Added -resume command line option.  This will start time all tasks\n\
      that were being timed when the application exited last.\n\
    + Projects are now associated with a project.  The project is now the\n\
      first column in the main window.\n\
    + Added option to round minutes to nearest minute, 5 minutes, etc\n\
      in reports window\n\
    + Added small css stylesheet to report html output.\n\
    + Added \"Last Two Weeks\", \"This Week & Last Week\" reports\n\
    + Reread gtkrc if -dir option is supplied\n\
    + Modified http function to use \"Host:\" required by web sites\n\
      that used virtual hosts, like www.cknudsen.com.  Also improved\n\
      error handling a little bit.\n\
    + Fixed font setting of text reports to properly use fixed-width font.\n\
    + Increased default size of report text window.\n\
    + Added link to GTimer home page in Help menu.\n\
09 Mar 2000:\n\
  - Release 1.1.5\n\
    + Improved idle handling.  The task list is no longer re-sorted when\n\
      selecting \"Revert.\"  Added a new \"Resume\" option that will toss\n\
      out the idle time but keep timing whatever tasks are being timed.\n\
    + Added tool to check for new version.  The app will automatically\n\
      check for a new version every 30 days.\n\
    + Added ability to view ChangeLog from Help menu\n\
04 May 1999:\n\
  - Release 1.1.4\n\
    + Oops.  Fixed typo is task menu pulldown that said \"seconds\" instead\n\
      of \"minutes.\"\n\
03 May 1999:\n\
  - Release 1.1.3\n\
    + Fixed bug where \\n chars could be included at the end of a task name\n\
    + Fixed bug where adding new tasks messes up the hide/unhide stuff\n\
    + Fixed bug where -nosplash would cause the main window\n\
      to not remember the correct window size.\n\
    + Added support for the X screen saver extension so idle detection\n\
      will now sense keyboard events instead of just mouse events\n\
    + Added support for I18N but need translators!\n\
    + Made some windows transient (for GTK+ 1.1/1.2 only) instead of\n\
      all toplevels\n\
    + Made animated clock optional\n\
    + Made toolbar optional\n\
    + Allowed main menus to be tearoffs (for GTK+ 1.1/1.2 only)\n\
    + Added -start option allowing you to specify one or more tasks\n\
      to start timing when the app starts\n\
    + Added support for -version and -help options\n\
    + Added missing install-sh file to distribution\n\
    + Added FAQ.html to distribution\n\
    + Added portions of a Win32 port patch\n\
17 Mar 1999:\n\
  - Release 1.1.2\n\
    + Added autoconf (configure) support\n\
    + Added back support for GTK 1.0 (and still works with GTK 1.1/1.2)\n\
24 Feb 1999:\n\
  - Release 1.1.1\n\
    + Added task unhide function to along with the hide function (added\n\
      in a previous release).\n\
    + Added support for accelerator keys.  (Thanks to Matt Martin\n\
      <mmartin@Calvin.SFC.Lehigh.Edu> for the original code.)\n\
    + Fixed support for double-clicking to switch to timing only\n\
      the newly selected task (GTK 1.1 problem).\n\
    + Fixed support for the task pulldown menu available by right-clicking\n\
      on a task in the main window (GTK 1.1 problem).\n\
04 Feb 1999:\n\
  - Release 1.1.0\n\
    + Now requires GTK 1.1.X\n\
    + Remembers width/height of main window as well as width of each\n\
      column in the task list of the main window.\n\
    + Double-click on a task to stop timing all other tasks and begin\n\
      timing the selected task\n\
    + Fixed bug for \"last month\" reports when run in January.\n\
10 May 1998:\n\
  - Release 0.98\n\
    + Added #ifdef for an API change in 1.0.1\n\
      thanks Stephen Robert Norris (srn@flibble.psrg.cs.usyd.edu.AU)\n\
    + Oops.  Forgot to include xextras.c in the distribution.\n\
10 May 1998:\n\
  - Release 0.97\n\
    + Added idle detect.  Enabled/Disabled from the \"Options\" pulldown\n\
      menu.  Will prompt user after 5 minutes of no mouse movements.\n\
      (Would be nice to watch keyboard, too...  maybe that's next.)\n\
    + Added autosave.  Enabled/Disabled from the \"Options\" pulldown menu.\n\
      Will save every 15 minutes (if changes are made and the idle\n\
      detection window is not up.)\n\
    + Set the application's icon from within the application.  There's\n\
      a different icon depending on whether or not any tasks are being\n\
      timed.\n\
    + Added handler for X I/O errors.  Data is now saved on X I/O\n\
      errors (like xkill).\n\
    + Fixed vertical resize problem on main window (status bar).\n\
06 April 1998:\n\
  - Release 0.96\n\
    + Added support for HTML reports (requires 'netscape' somewhere in\n\
      your path)\n\
    + Save configuration on exit (sort mode, etc.)\n\
    + Added print option from reports\n\
    + Enabled word wrap on annotation entry (required GTK-0.99.9)\n\
    + Enabled word wrap on report display (required GTK-0.99.9)\n\
    + Added total time for the day at the bottom of the main window\n\
    + Updated toolbar icons (reduced number of colors for better use\n\
      on 8-bit displays: should use only 28 colors other than b&w)\n\
    + Fixed bug that caused gargbage characters to appear at the end of\n\
      some annotations (just use vi to clean up the .ann files of this\n\
      has happened to you)\n\
    + Added a brief man page\n\
    + Set default for new tasks names as \"Unnamed Task\" and set focus\n\
      to the text entry widget\n\
    + Added a splash screen on app startup (can be disabled with\n\
      -nosplash argument)\n\
24 March 1998:\n\
  - Release 0.95\n\
    + Sort tasks by clicking on column headers.\n\
    + Added support for multiline annotations.\n\
    + Replaced label widget with text widget in the report display\n\
      window.  (This allows for X copy/paste).\n\
    + Added \"Annotate\" to Task pulldown menu.\n\
    + Fixed various memory leaks/bugs.\n\
    + Fixed 0.94 bug where stop button tried to start timing the\n\
      selected task.\n\
    + Fixed all weekdays showing up as \"Mon\" in some reports.\n\
    + Set application class to \"GTimer.gtimer\".  This should help with\n\
      window managers (such as WindowMaker).\n\
    + Added icon in toolbar for editing task names.\n\
    + Added icon in toolbar for adding new tasks.\n\
18 March 1998:\n\
  - Release 0.94\n\
    + Renamed application \"GTimer\" from \"TaskTimer\" after being notified\n\
      that \"TaskTimer\" is a registered trademark of Time/Systems\n\
      International.\n\
    + Added support for annotations that can be displayed in reports.\n\
    + Used a memory debugging library to remove some memory leaks.\n\
    + Added pulldown menus for right mouse click on a task.\n\
      [Code provided by Zach Beane (xach@mint.net)]\n\
    + Double click on a task to edit the task.\n\
      [Code provided by Zach Beane (xach@mint.net)]\n\
    + Changed font in report window to be fixed size for better display.\n\
13 March 1998:\n\
  - Release 0.93\n\
    + Rearranged UI: Added \"Task\" and \"Report\" pulldown menus and toolbar\n\
      with icons.\n\
    + Added saving of reports to a file.\n\
    + Reports now use H:MM:SS time rather than H:MM.\n\
    + Updated confirm and error icons.\n\
    + Fixed handling of date change at midnight.\n\
10 March 1998:\n\
  - Bugfix release 0.91\n\
    + comment out tooltips so it will compile on GTK-0.99.5\n\
    + Create ~/.gtimer if it does not exist\n\
      (Thanks Zach Beane <xach@mint.net>)\n\
09 March 1998:\n\
  - Initial Release 0.90\n\
";
