/*
 * GTimer
 *
 * Copyright:
 *      (C) 1999 Craig Knudsen, cknudsen@radix.net
 *      See accompanying file "COPYING".
 *
 *      This program is free software; you can redistribute it and/or
 *      modify it under the terms of the GNU General Public License
 *      as published by the Free Software Foundation; either version 2
 *      of the License, or (at your option) any later version.
 *
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 *
 *      You should have received a copy of the GNU General Public License
 *      along with this program; if not, write to the
 *      Free Software Foundation, Inc., 59 Temple Place,
 *      Suite 330, Boston, MA  02111-1307, USA
 *
 * Description:
 *	This file is generated AUTOMATICALLY from ./txt2h.pl.
 *	DO NOT EDIT THIS FILE!!!!
 *
  ****************************************************************************/

static char *changelog_text = "\
09 Mar 2003:\n\
  - Release 1.1.6\n\
    + Added -resume command line option.  This will start time all tasks\n\
      that were being timed when the application exited last.\n\
    + Projects are now associated with a project.  The project is now the\n\
      first column in the main window.\n\
    + Added option to round minutes to nearest minute, 5 minutes, etc\n\
      in reports window\n\
    + Added small css stylesheet to report html output.\n\
    + Added \"Last Two Weeks\", \"This Week & Last Week\" reports\n\
    + Reread gtkrc if -dir option is supplied\n\
    + Modified http function to use \"Host:\" required by web sites\n\
      that used virtual hosts, like www.cknudsen.com.  Also improved\n\
      error handling a little bit.\n\
09 Mar 2000:\n\
  - Release 1.1.5\n\
    + Improved idle handling.  The task list is no longer re-sorted when\n\
      selecting \"Revert.\"  Added a new \"Resume\" option that will toss\n\
      out the idle time but keep timing whatever tasks are being timed.\n\
    + Added tool to check for new version.  The app will automatically\n\
      check for a new version every 30 days.\n\
    + Added ability to view ChangeLog from Help menu\n\
04 May 1999:\n\
  - Release 1.1.4\n\
    + Oops.  Fixed typo is task menu pulldown that said \"seconds\" instead\n\
      of \"minutes.\"\n\
03 May 1999:\n\
  - Release 1.1.3\n\
    + Fixed bug where \\n chars could be included at the end of a task name\n\
    + Fixed bug where adding new tasks messes up the hide/unhide stuff\n\
    + Fixed bug where -nosplash would cause the main window\n\
      to not remember the correct window size.\n\
    + Added support for the X screen saver extension so idle detection\n\
      will now sense keyboard events instead of just mouse events\n\
    + Added support for I18N but need translators!\n\
    + Made some windows transient (for GTK+ 1.1/1.2 only) instead of\n\
      all toplevels\n\
    + Made animated clock optional\n\
    + Made toolbar optional\n\
    + Allowed main menus to be tearoffs (for GTK+ 1.1/1.2 only)\n\
    + Added -start option allowing you to specify one or more tasks\n\
      to start timing when the app starts\n\
    + Added support for -version and -help options\n\
    + Added missing install-sh file to distribution\n\
    + Added FAQ.html to distribution\n\
    + Added portions of a Win32 port patch\n\
17 Mar 1999:\n\
  - Release 1.1.2\n\
    + Added autoconf (configure) support\n\
    + Added back support for GTK 1.0 (and still works with GTK 1.1/1.2)\n\
24 Feb 1999:\n\
  - Release 1.1.1\n\
    + Added task unhide function to along with the hide function (added\n\
      in a previous release).\n\
    + Added support for accelerator keys.  (Thanks to Matt Martin\n\
      <mmartin@Calvin.SFC.Lehigh.Edu> for the original code.)\n\
    + Fixed support for double-clicking to switch to timing only\n\
      the newly selected task (GTK 1.1 problem).\n\
    + Fixed support for the task pulldown menu available by right-clicking\n\
      on a task in the main window (GTK 1.1 problem).\n\
04 Feb 1999:\n\
  - Release 1.1.0\n\
    + Now requires GTK 1.1.X\n\
    + Remembers width/height of main window as well as width of each\n\
      column in the task list of the main window.\n\
    + Double-click on a task to stop timing all other tasks and begin\n\
      timing the selected task\n\
    + Fixed bug for \"last month\" reports when run in January.\n\
10 May 1998:\n\
  - Release 0.98\n\
    + Added #ifdef for an API change in 1.0.1\n\
      thanks Stephen Robert Norris (srn@flibble.psrg.cs.usyd.edu.AU)\n\
    + Oops.  Forgot to include xextras.c in the distribution.\n\
10 May 1998:\n\
  - Release 0.97\n\
    + Added idle detect.  Enabled/Disabled from the \"Options\" pulldown\n\
      menu.  Will prompt user after 5 minutes of no mouse movements.\n\
      (Would be nice to watch keyboard, too...  maybe that's next.)\n\
    + Added autosave.  Enabled/Disabled from the \"Options\" pulldown menu.\n\
      Will save every 15 minutes (if changes are made and the idle\n\
      detection window is not up.)\n\
    + Set the application's icon from within the application.  There's\n\
      a different icon depending on whether or not any tasks are being\n\
      timed.\n\
    + Added handler for X I/O errors.  Data is now saved on X I/O\n\
      errors (like xkill).\n\
    + Fixed vertical resize problem on main window (status bar).\n\
06 April 1998:\n\
  - Release 0.96\n\
    + Added support for HTML reports (requires 'netscape' somewhere in\n\
      your path)\n\
    + Save configuration on exit (sort mode, etc.)\n\
    + Added print option from reports\n\
    + Enabled word wrap on annotation entry (required GTK-0.99.9)\n\
    + Enabled word wrap on report display (required GTK-0.99.9)\n\
    + Added total time for the day at the bottom of the main window\n\
    + Updated toolbar icons (reduced number of colors for better use\n\
      on 8-bit displays: should use only 28 colors other than b&w)\n\
    + Fixed bug that caused gargbage characters to appear at the end of\n\
      some annotations (just use vi to clean up the .ann files of this\n\
      has happened to you)\n\
    + Added a brief man page\n\
    + Set default for new tasks names as \"Unnamed Task\" and set focus\n\
      to the text entry widget\n\
    + Added a splash screen on app startup (can be disabled with\n\
      -nosplash argument)\n\
24 March 1998:\n\
  - Release 0.95\n\
    + Sort tasks by clicking on column headers.\n\
    + Added support for multiline annotations.\n\
    + Replaced label widget with text widget in the report display\n\
      window.  (This allows for X copy/paste).\n\
    + Added \"Annotate\" to Task pulldown menu.\n\
    + Fixed various memory leaks/bugs.\n\
    + Fixed 0.94 bug where stop button tried to start timing the\n\
      selected task.\n\
    + Fixed all weekdays showing up as \"Mon\" in some reports.\n\
    + Set application class to \"GTimer.gtimer\".  This should help with\n\
      window managers (such as WindowMaker).\n\
    + Added icon in toolbar for editing task names.\n\
    + Added icon in toolbar for adding new tasks.\n\
18 March 1998:\n\
  - Release 0.94\n\
    + Renamed application \"GTimer\" from \"TaskTimer\" after being notified\n\
      that \"TaskTimer\" is a registered trademark of Time/Systems\n\
      International.\n\
    + Added support for annotations that can be displayed in reports.\n\
    + Used a memory debugging library to remove some memory leaks.\n\
    + Added pulldown menus for right mouse click on a task.\n\
      [Code provided by Zach Beane (xach@mint.net)]\n\
    + Double click on a task to edit the task.\n\
      [Code provided by Zach Beane (xach@mint.net)]\n\
    + Changed font in report window to be fixed size for better display.\n\
13 March 1998:\n\
  - Release 0.93\n\
    + Rearranged UI: Added \"Task\" and \"Report\" pulldown menus and toolbar\n\
      with icons.\n\
    + Added saving of reports to a file.\n\
    + Reports now use H:MM:SS time rather than H:MM.\n\
    + Updated confirm and error icons.\n\
    + Fixed handling of date change at midnight.\n\
10 March 1998:\n\
  - Bugfix release 0.91\n\
    + comment out tooltips so it will compile on GTK-0.99.5\n\
    + Create ~/.gtimer if it does not exist\n\
      (Thanks Zach Beane <xach@mint.net>)\n\
09 March 1998:\n\
  - Initial Release 0.90\n\
";
